### ISSUE TITLE
Test GRP1

### ISSUE THREAD

**Issue by noah-barberini-cpnv** [noah-barberini-cpnv/GPR1-SocialNetwork#1]
Tous les tests passent sauf le test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException qui, même si je throw une nouvelle expection dans le constructor ne passe pas.

https://github.com/noah-barberini-cpnv/GPR1-SocialNetwork/commit/bf638c5ea5251bd17f6a05c2bdb6d27a78679417

**Comment by NicolasGlassey** [comment]
@noah-barberini-cpnv 

Bonjour Noah,

J'ai pris en compte cette issue pour l'évaluation.

Bonne suite de week-end !
